name: .NET CI

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'  # or specify your SDK version

      - name: Restore solution
        run: dotnet restore FlexyBoxProject.sln

      - name: Build solution
        run: dotnet build FlexyBoxProject.sln --no-restore --configuration Release

      - name: Run Web API
        run: dotnet run --project FlexyBoxProject/FlexyBoxProject/FlexyBoxProject.csproj --no-build --configuration Release
